### ISSUE TITLE
The new note (+) button is very offset to left

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [Nriver/trilium-enhancement#2]
As you can see on the screenshot, for any note, when i enabled this trilium-enhancement module or however it is called, this started to be an issue, before this it worked fine. So I assume the problem is here. I installed this because it is recommended in bing-daily-theme git repo
![image](https://github.com/user-attachments/assets/89e1d825-5a45-4de8-85c1-5e4e9d89ca1e)

Thank you in advance!

**Comment by Nriver** [comment]
This is a feature as explained [here](https://github.com/Nriver/trilium-enhancement#new-note-button). If you do not like it, just delete the [related note](https://github.com/Nriver/trilium-enhancement/blob/main/Experience%20Enhancement%20Kit%20%20%E4%BD%93%E9%AA%8C%E5%A2%9E%E5%BC%BA%E5%A5%97%E4%BB%B6/Action%20Enhancements%20%20%E6%93%8D%E4%BD%9C%E5%A2%9E%E5%BC%BA/new%20note%20button%20to%20front%20%20%E6%96%B0%E5%A2%9E%E7%AC%94%E8%AE%B0.css).

**Comment by suhli** [comment]
or use this instead:
```css
/* 默认：占位、不显示、不可点击 */
.desktop .add-note-button{
  order: -10;
  margin-right: 6px;
  visibility: hidden;
  display: inline-block !important;
  pointer-events: none;
}
/* hover 时：显示、可点 */
.fancytree-node:hover .add-note-button {
  visibility: visible;
  pointer-events: auto;
}
```

<img width="111" height="34" alt="Image" src="https://github.com/user-attachments/assets/5385e651-92c3-43a3-9396-59f76560f1fa" />

<img width="120" height="31" alt="Image" src="https://github.com/user-attachments/assets/2851d252-8778-4761-91dd-fb2a3c9cef6e" />
