### ISSUE TITLE
Better Tree Styles

### ISSUE THREAD

**Issue by wfthkttn** [Nriver/trilium-enhancement#3]
Made the tree more readable with nested hover while keeping it subtle.
Decreased size of expanders and tweaked indentations 

```css
.fancytree-container > li > ul li {
    border-left: 2px solid #282828;
    border-radius: 3px 0 0 3px;
}
.fancytree-container > li > ul li:hover {
    border-left: 2px solid #304830;
}

/* increase indent between layers below first */
.fancytree-container > li > ul > li > ul li {
    margin-left: 5px;
}
/* move nodes left to eliminate gaps */
.fancytree-node {
    margin-left:-4px;
}
/* calm down, expander */
.fancytree-expander {
    filter: brightness(0.58);
    transform: scale(0.7);
    margin-left:-2px;
    margin-right:-6px;
}
```

![Image](https://github.com/user-attachments/assets/61442c93-ea3c-4dca-b01d-090c027c21ef)
